### ISSUE TITLE
Chat broke immediately after subscribing to a 4th channel

### ISSUE THREAD

**Issue by Goofyd00d** [night/BetterTTV#155]
I refreshed after subscribing to a 4th channel and now I get the following message in the chat window
"BetterTTV encountered an error reading chat. The developer has been sent a log of this action. Please try clearing your cookies and cache."
I have cleared out my cookies and caches repeatedly, went to github from the page that appeared when I googled the message and used the "fixed code" into the console, and updated to the newest version on your website (6.8R27)

Nothing has made any changes.

**Comment by Goofyd00d** [comment]
I fixed by downloading an older version from the chrome store, would still be interested in a fix for the newest version,

**Comment by night** [comment]
You didn't fix it by doing that. Twitch pushed an update which BetterTTV was incompatible with, and then pulled it a short while later. We're still working to be compatible with the upcoming changes.
