### ISSUE TITLE
Option to hide "Reruns"

### ISSUE THREAD

**Issue by Mitsuma** [night/betterttv#2496]
It is a new feature and I'm not sure if twitch has something planned.
Somehow I think Twitch might not give us the option so I want to request if it's possible to get an option to hide the new vodcasts as they currently clutter live section in your follower list.

It would be a great addition and I'm sure there are others that don't want some VoD playlist on their live feed.

**Comment by Spliffs** [comment]
yes please! I do not want to see any vodcasts in my following list. If I wanted to watch vods, I know where they are. :D Silly Twitch LUL

**Comment by Snizh-Fize** [comment]
any news on this feature? those vodcasts are a joke and i don't know why they are being treated like live channels...

**Comment by colincreighton** [comment]
I would also love to see this on BTTV. Looks like it is possible with some undocumented API filtering https://discuss.dev.twitch.tv/t/vodcasts-not-reported-as-playlist-streams-in-api/10603

**Comment by Andrey-Sisoyev** [comment]
I guess this is hard to implement, or against BTTV authors' views. I see no other reason to have this obviously needed feature missing. 
A possible workaround for those, who are still waiting for it: just block every streamer who streams vodcasts. There is an extension for Chrome for that: "Hide unwanted streams on Twitch"
You can also vote for this feature here: https://github.com/LinogeFly/hide-unwanted-streams-on-twitch/issues/18

**Comment by ericchase** [comment]
I have implemented this myself with a userscript.

**Comment by qvatch** [comment]
Or perhaps filter them to their own section "Live Channels", "Live VODs", "Live Hosts", etc.

**Comment by dsnvwlmnt** [comment]
Anytime now... I acquired BTTV strictly for this. Turns out it's still not implemented. :(

**Comment by SlidingHorn** [comment]
This feature is almost a must anymore...half of twitch seems to be VODs/replays lately, and it's extra annoying to visually "sort through" them

**Comment by Andrey-Sisoyev** [comment]
@SlidingHorn there's a beautiful extension for Chrome "Unwanted Twitch" - it solves this feature, as well as many others. Already, I was able to find many great small channels thanks to the filtering it provides.

**Comment by Mitsuma** [comment]
> This feature is almost a must anymore...half of twitch seems to be VODs/replays lately, and it's extra annoying to visually "sort through" them

You might just want to install FFZ in addition to BTTV. 
It actually offers to hide re-runs and I think vodcasts as well.

**Comment by ericchase** [comment]
I concur, FFZ handles this and so does Unwanted Twitch. I have them both. I think this is the optimal solution right now.

**Comment by whitecrownclown** [comment]
I put up a PR for this : #3376

**Comment by night** [comment]
Due to the intricacies involved in querying additional results from Twitch's GQL API and having to manage numerous page renders as the directory is browsed, it seems unlikely that we could build a good UX around extending the directory view. Results would pop in and out, and if there are many re-runs shown the directory may look broken. Further, re-runs are not really used much these days and there have been rumors of Twitch discontinuing support for them for a while.
