### ISSUE TITLE
Pinned Highlighted Messages No Longer Working

### ISSUE THREAD

**Issue by MrSelenix** [night/betterttv#3879]
As the title suggests, the "Pinned Highlighted Messages" setting is no longer pinning any messages despite being on. Issue started (well.... stopped technically) 2 days ago and has not pinned any highlighted messages since. 
I have unchecked the setting and restarted Chrome, then turned the setting back on again.
I have forced BTTV to crash via task manager.
I have removed and reinstalled the extension.
Messages still do not get pinned.

BetterTTV v7.2.78
Google Chrome: 81.0.4044.138 (Official Build) (64-bit) (cohort: Stable)
Windows 7

**Comment by Nareese** [comment]
This bug has been fixed in the latest version released last night (7.2.79).  If you are using Chrome, however, you will have to wait for Google to approve and release this new version, which can take up to 2-3 days.  If you are using any other browser, it should already have updated, and if not, you can force an update check.

**Comment by MrSelenix** [comment]
Ahhh. Lovely thanks for that info. Was just about to update to say it was working in Firefox.

**Comment by guniu** [comment]
> This bug has been fixed in the latest version released last night (7.2.79). If you are using Chrome, however, you will have to wait for Google to approve and release this new version, which can take up to 2-3 days.

@Nareese what if I have 7.2.79 on chrome and it's still not working?
