### ISSUE TITLE
Modding widget with right click does not appear.

### ISSUE THREAD

**Issue by hatiundskoll** [night/betterttv#3953]
When right clicking on a name, the modding widget does not appear. 

*Using firefox as well

**Comment by night** [comment]
this is already fixed in latest version for firefox.

**Comment by hatiundskoll** [comment]
I am currently using the latest version, and it still does not work I'm afraid.

**Comment by night** [comment]
Make sure you're on v7.2.81. I just tried using the old channel page, new channel page, and mod view. It works in all 3 on latest version in Firefox.

**Comment by hatiundskoll** [comment]
I am not entirely sure how or why, but by swapping to mod view made it start to work. I typically don't use mod view so i never thought to try that. Thank you for your help!
