### ISSUE TITLE
Emotes blurry in new emotes menu

### ISSUE THREAD

**Issue by movedoa** [night/betterttv#4857]
The emotes appear blurry in the new menu. They are fine in the twitch version of the menu.

![grafik](https://user-images.githubusercontent.com/13309951/133985485-9432906a-e913-4858-8adb-1cf9ea919ded.png)

The problem is the width and height settings, they are set to 32px but this should be max-height/max-width to just clamp oversized ones and don't blow up smaller ones

![grafik](https://user-images.githubusercontent.com/13309951/133985448-75c5cb95-c532-48f1-9d9e-a464343b0a88.png)

**Comment by night** [comment]
The blurriness is fixed as of 7.4.6. You may need to check for the latest extension updates in your browser.

**Comment by movedoa** [comment]
> 
> 
> The blurriness is fixed as of 7.4.6. You may need to check for the latest extension updates in your browser.

I am on 7.4.7 and was when i created this issue, so this is not fixed.
