### ISSUE TITLE
Tab autocomplete for emotes not working

### ISSUE THREAD

**Issue by Dragoonseal** [night/betterttv#5514]
Chrome Version 103.0.5060.114 (Official Build) (64-bit)
Windows 10
BTTV Version 7.4.29

Normally I'll type out most of or all of an emote and then press tab to complete it or correct the capitalization, but currently that just gives me a "No Matches" popup. Works for names though.

Guessing it's related to other issues people reported, but weirdly I don't have any of the same issues. My emoji show up fine, deleted messages show up fine. It's just the tab autocomplete for emotes so far as I've noticed.

EDIT: Never mind the deleted messages bit, they only show for me on a channel I mod for, they don't show up elsewhere.

**Comment by derpyderpaderp** [comment]
Same issue with just twitch emotes it seems. Bttv emotes work with tab. For instance (feelsbadman) works whereas (Kappa) shows nothing

**Comment by night** [comment]
fixed via d17d0c65c15d3b885c0eb99c1b9d958d3342de9c

**Comment by Dragoonseal** [comment]
@night This doesn't seem to have fixed the autocomplete. I gave it a day and I'm on Version 7.4.31 now which has fixed the other issues people were posting about, but tab autocomplete still isn't working for official Twitch emotes.

**Comment by Dragoonseal** [comment]
Fixed as of Version 7.4.32. 👍

**Comment by derpyderpaderp** [comment]
> Fixed as of Version 7.4.32. 👍

Okay most are fixed for me, besides the original Kappa itself, is yours working?

**Comment by Dragoonseal** [comment]
> > Fixed as of Version 7.4.32. 👍
> 
> Okay most are fixed for me, besides the original Kappa itself, is yours working?

I can tab autocomplete the Kappa emote, yes.
