### ISSUE TITLE
Request Review on Personal Emote uploaded by someone else throwing 403 Forbidden

### ISSUE THREAD

**Issue by TennisMexican** [night/betterttv#5906]
Was attempting to add an emote to my personal emotes and noticed there's a Request Review button on emotes that I didn't upload but when I click it, nothing happens.

When looking at the Developer Console in Chrome, it appears to be throwing a 403 Forbidden error message.

I tried on multiple different emotes uploaded by separate users and they all behaved the same.

One Example:
https://betterttv.com/emotes/5fee1e75be65982e48cede2d

![image](https://user-images.githubusercontent.com/77464872/215286637-69b60a36-9d7a-4e8b-94dc-96bffef2fe69.png)

**Comment by night** [comment]
I believe the UI should be fixed now. Only channel owners are currently able to request a manual review of their emotes.

**Comment by TennisMexican** [comment]
I still get the pop-up saying I need to request review before adding someone else's emote to my personal emotes. Even tried going Incognito and got the same results.

**Comment by night** [comment]
I see the problem. A library update broke the button's disabled state. It should be fixed now.

**Comment by TennisMexican** [comment]
Yep, that did it, now it’s disabled again! Thanks!
